config/routes.rb
Interviewr::Application.routes.draw do

  resources :sessions
  resources :interviewee_sessions

  match 'end' => 'sessions#destroy', :as => :end
  match 'done' => 'interviewee_sessions#destroy', :as => :done
  match 'interviewer' => 'sessions#show', :as => :current_session
  match 'interviewee' => 'interviewee_sessions#show'
  match 'busy' => 'static#busy', :as => :busy
  match 'no_session' => 'static#no_session', :as => :no_session
  match 'disconnected' => 'static#disconnected', :as => :disconnected
  match ':random' => 'interviewee_sessions#new', :as => :new_interviewee_session
  match 'sess/:random' => 'interviewee_sessions#create', :as => :link_session
  match 'sessions' => 'static#no_session'
  match 'sessions/:foo' => 'static#no_session'

  root :to => 'sessions#new'

end

app/models/code.rb
class Code < ActiveRecord::Base
  attr_accessible :code, :language
end

app/models/interviewee_session.rb
class IntervieweeSession < ActiveRecord::Base
  attr_accessible :random, :name
  has_one :room
  validate :session_is_in_system
  validates_uniqueness_of :random
  #Validate the uniqueness of random and validate that random exists in sessions table

  private
  def session_is_in_system
    if (Session.find_by_random(self.random) == nil)
      errors.add(:double, "is not an active in the system")
      IntervieweeSession.find_by_random(self.random).destroy if IntervieweeSession.find_by_random(self.random) != nil
      return false
    end
    return true
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :interviewee_session_id, :name, :openTokID, :session_id
  belongs_to :session
  belongs_to :interviewee_session, :dependent => :destroy



end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :company, :interviewer, :random
  validates_uniqueness_of :random
  has_one :room, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def config_opentok
    if @opentok.nil?

      @opentok = OpenTok::OpenTokSDK.new "22586622", "f6bfae97fc2a3140a327d9d3e56d88ced8b86611"

    end
  end
  helper_method :config_opentok

  def current_viewer_session
    @current_viewer_session ||= Session.find_by_random(session[:random]) if session[:random]
  end
  helper_method :current_viewer_session

  def current_viewee_session
    @current_viewee_session ||= Session.find_by_random(session[:viewee_random]) if session[:viewee_random]
  end
  helper_method :current_viewee_session

  def interviewer?
    current_viewer_session
  end
  helper_method :interviewer?

  def interviewee?
    current_viewee_session
  end
  helper_method :interviewee?

  def interviewer_name
    @interviewer_name ||= Session.find_by_random(session[:viewee_random]).interviewer if session[:viewee_random]
  end
  helper_method :interviewer_name

  def interviewer_co
    @interviewer_co ||= Session.find_by_random(session[:viewee_random]).company if session[:viewee_random]
  end
  helper_method :interviewer_co


end

app/controllers/code_controller.rb
class CodeController < ApplicationController
end

app/controllers/interviewee_sessions_controller.rb
class IntervieweeSessionsController < ApplicationController
	def new
		@random = params[:random]
		@session = Session.find_by_random(@random)
		if (@session == nil)
			flash[:alert] = "You have tried to connect to an interview that doesn't exist. Create a new one?"
			redirect_to('/')
		end
		@interviewee_session = IntervieweeSession.new
	end

	def destroy
		@interviewee_session = IntervieweeSession.find_by_random(session[:viewee_random])
		@session = Session.find_by_random(session[:viewee_random])
		@interviewee_session.destroy if @interviewee_session != nil
		session[:viewee_random] = nil
	end

	def create
		if (session[:random] != nil)
			flash[:alert] = "You are already hosting an interview."
			redirect_to('/interviewer')
			return
		end

		@interviewee_session = IntervieweeSession.new(params[:interviewee_session])
		random = @interviewee_session.random

		if @interviewee_session.save
			session[:viewee_random] = random
			r = Room.find_by_name(@interviewee_session.random)
			r.interviewee_session_id = @interviewee_session.id
			r.save
			redirect_to('/interviewee')
		else
			destroy
			if (Session.find_by_random(random) == nil)
				flash[:alert] = "You have tried to connect to an interview that doesn't exist. Create a new one?"
				redirect_to('/')
			else
				flash[:alert] = "You have tried to connect to an interview someone already connected to. Create a new one?"
      			redirect_to('/')
      		end
		end

	end

	def show
		if (Session.find_by_random(session[:viewee_random]) == nil)
			destroy
			if (session[:random] != nil)
				flash[:alert] = "You are already hosting an interview."
				redirect_to('/interviewer')
			else
				flash[:alert] = "You have been disconnected."
				redirect_to('/')
			end
		else
			config_opentok
			@interviewee_session = IntervieweeSession.find_by_random(session[:viewee_random])
			@token = @opentok.generate_token :session_id => @interviewee_session.room.openTokID
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		if interviewer?
			redirect_to('/interviewee', :alert => 'You still have a session going on.')
		end
		if interviewee?
			redirect_to('/interviewee', :alert => 'You are already participating in an interview.')
		end
		@session = Session.new
	end
	def create
		if (session[:viewee_random] != nil)
			redirect_to('/interviewee', :alert => 'You are already participating in an interview.')
			return
		end

		@session = Session.new(params[:session])
		@session.random = generate_id
		if (Session.find_by_random(@session.random) != nil)
			@session.random = generate_id
		end
		session[:random] = @session.random
		config_opentok

		@new_room = Room.new
		location = "http://interviewr.us/"
		session_properties = {OpenTok::SessionPropertyConstants::P2P_PREFERENCE => "enabled"}
		session = @opentok.create_session(location, session_properties)
		@new_room.openTokID = session.session_id
		@new_room.name = @session.random
		@session.save
		@new_room.session_id = @session.id
		@new_room.save
		redirect_to('/interviewer', :notice => 'The URL is interviewr.us/' + @session.random)
	end

	def show
		@session = Session.find_by_random(session[:random])
		config_opentok
		@token = @opentok.generate_token :session_id => @session.room.openTokID
	end 

	def destroy
		@session = Session.find_by_random(session[:random])
		session[:random] = nil
		@session.destroy
		redirect_to('/', :notice => 'The interview has ended.  Start another?')
	end

	private
	def generate_id
		a = (0...36).map{|i|i.to_s 36}
		s = ''
		(0...(rand(10)+15)).each do |i|
			s += a[rand(36)]
		end
		return s
	end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_helper.rb
module CodeHelper
end

app/helpers/interviewee_session_helper.rb
module IntervieweeSessionHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/interviewee_sessions/_chat.html.erb
    <div id='messagesDiv'></div>
    <input type='text' id='messageInput' placeholder='Message'>
    <script>
      var myDataRef = new Firebase('https://interviewr.firebaseio.com/<%=@interviewee_session.random%>');
      myDataRef.push()
      $('#messageInput').keypress(function (e) {
        if (e.keyCode == 13) {
          var name = "<%= escape_javascript(@interviewee_session.name) %>";
          var text = $('#messageInput').val();
          myDataRef.push({name: name, text: text});
          $('#messageInput').val('');
        }
      });
      myDataRef.on('child_added', function(snapshot) {
        var message = snapshot.val();
        displayChatMessage(message.name, message.text);
      });
      function displayChatMessage(name, text) {
        $('<div/>').text(text).prepend($('<em/>').text(name+': ')).appendTo($('#messagesDiv'));
        $('#messagesDiv')[0].scrollTop = $('#messagesDiv')[0].scrollHeight;
      };
    </script>

app/views/interviewee_sessions/_lang.html.erb
<select name="Language" id="langDrop">
  <option value = "text/x-csrc">C</option>
  <option value = "text/x-c++src">C++</option>
  <option value = "text/x-java">Java</option>
  <option value = "text/javascript">JavaScript</option>
  <option value = "text/x-ocaml">OCaml</option>
  <option value = 'text/x-python'>Python</option>
  <option value = 'text/x-scala'>Scala</option>
  <option value = "text/x-ruby">Ruby</option>
  <option value = 'text/x-sql'>SQL</option>
</select>  

<script>
  var langRef = new Firebase("https://interviewr.firebaseio.com/<%= @interviewee_session.random + 'lang'%>");
  var extension = "c"
  $("#langDrop").change (function () {
    var newSyntax = $("#langDrop option:selected").val();
    langRef.set({"lang": newSyntax});
  });

  langRef.on('value', function(snapshot)  {
    if (snapshot.val() !== null)
    {
      $("#langDrop").val(snapshot.val().lang);
      codeMirror.setOption("mode", $("#langDrop").val());
      if ($("#langDrop").val() == "text/x-csrc") extension = "c";
      if ($("#langDrop").val() == "text/x-java") extension = "java";
      if ($("#langDrop").val() == "text/x-javascript") extension = "js";
      if ($("#langDrop").val() == "text/x-ocaml") extension = "ocaml";
      if ($("#langDrop").val() == "text/x-python") extension = "py";
      if ($("#langDrop").val() == "text/x-scala") extension = "scala";
      if ($("#langDrop").val() == "text/x-c++src") extension = "cpp";
      if ($("#langDrop").val() == "text/x-ruby") extension = "rb";
      if ($("#langDrop").val() == "text/x-sql") extension = "sql";
    }
  });
</script>

app/views/interviewee_sessions/_textedit.html.erb
  <div class="btn-group">
    <button class="btn notepad-open">Open File</button>
    <button class="btn notepad-save">Save Code</button>
  </div>
  <script type="text/javascript">
  var curr_file;
$(".notepad-open").click(function(){
   filepicker.pick({}, function(fpfile){
      curr_file = fpfile;
      $(".notepad-title").text(fpfile.filename);
      $(".notepad-reload").removeClass("disabled");
      $("#notepad").val("Loading...").attr("disabled", "disabled");
      filepicker.read(curr_file, function(contents){
         firepad.setText(contents);
      });
   });
});
$(".notepad-save").click(function(){
  var btext = $(this).children("span");
  btext.text("Saving...");
  filepicker.store(firepad.getText(),
      {filename:'interviewr.' + extension, location: 'S3'},
      function(stored_file){
          filepicker.export(stored_file, {mimetype: 'plain-text/*'}, function(fpfile) {
              $(".notepad-title").text(fpfile.filename);
              btext.text("Saved");
              curr_file = fpfile;
          }
      );
  });
});
  </script>

<%= render :partial=>"lang" %><br />

<div id="firepad"></div>

  <script>
    //// Initialize Firebase.
    var firepadRef = new Firebase("https://interviewr.firebaseio.com/<%= @interviewee_session.random + 'firepad'%>");

    //// Create CodeMirror (with lineWrapping on).
    var codeMirror = CodeMirror(document.getElementById('firepad'), {
      lineNumbers: true,
      mode: 'javascript'
    });

    // Create a random ID to use as our user ID (we must give this to firepad and FirepadUserList).
    var userId = Math.floor(Math.random() * 9999999999).toString();

    //// Create Firepad (with rich text features and our desired userId).
    var firepad = Firepad.fromCodeMirror(firepadRef, codeMirror);

    /* //// Create FirepadUserList (with our desired userId).
    var firepadUserList = FirepadUserList.fromDiv(firepadRef.child('users'),
        document.getElementById('userlist'), userId);
    */

    //// Initialize contents.

    /* firepad.on('ready', function() {
      if (firepad.isHistoryEmpty()) {
        firepad.setText('// Check out the user list to the left!');
      }
    }); */

  </script>

app/views/interviewee_sessions/_video.html.erb
        <div class="container-fluid">
        <div class="row-fluid">
<div id="videos">
        <div id="myPublisherDiv"></div>
        <div id="otherUser"></div>
</div>

        <script type="text/javascript">
          // Initialize API key, session, and token...
          // Think of a session as a room, and a token as the key to get in to the room
          // Sessions and tokens are generated on your server and passed down to the client
          var apiKey = "22586622";
          var sessionId = "<%=@interviewee_session.room.openTokID%>";
          var token = "<%= @token %>" ;

          // Enable console logs for debugging
TB.setLogLevel(TB.DEBUG);

// Initialize session, set up event listeners, and connect
var session = TB.initSession(sessionId);
session.addEventListener('sessionConnected', sessionConnectedHandler);
session.addEventListener('streamCreated', streamCreatedHandler);
session.connect(apiKey, token);
function sessionConnectedHandler(event) {
  var publisher = TB.initPublisher(apiKey, 'myPublisherDiv');
  session.publish(publisher);
  var pub = document.getElementById(publisher.id);
  pub.style.width = "100px";
  pub.style.height = "66px";
  pub.style.position = "absolute";
  pub.style.z-index = "2";
  

  // Subscribe to streams that were in the session when we connected
  subscribeToStreams(event.streams);
}

function streamCreatedHandler(event) {
  // Subscribe to any new streams that are created
  subscribeToStreams(event.streams);
}

function subscribeToStreams(streams) {
  for (var i = 0; i < streams.length; i++) {
    // Make sure we don't subscribe to ourself
    if (streams[i].connection.connectionId == session.connection.connectionId) {
      return;
    }

    // Subscribe to the stream
    var oUser =session.subscribe(streams[i], "otherUser");
    var user = document.getElementById(oUser.id);
    user.style.width = "300px";
    user.style.height = "200px";
    user.style.position = "absolute";
    user.style.z-index = "1";
  }
}
</script>

app/views/interviewee_sessions/destroy.html.erb
<div id="settings-container">
	<div id="settings">
		<% if @session != nil %>
			<h1>Thank you for interviewing with <%= @session.interviewer %> from <%= @session.company %>.</h1>
		<% else %>
			<h1>Thank you for interviewing.</h1>
		<% end %>
		<h2>Have a nice day.</h2>
	</div>
</div>

app/views/interviewee_sessions/new.html.erb
<div id="settings-container">
	<div id="settings">
<h1>You are interviewing with <%= @session.interviewer %> from <%= @session.company %>.</h1>
<h2>Good luck!</h2>
	<%= simple_form_for(@interviewee_session, :html => { :class => 'form-horizontal' }) do |f| %>
	  <%= f.input :name, label: "your name" %>
	  <%= f.input :random, :as => :hidden, :input_html => { :value => @random } %>
	  <div class="form-actions">
	    <%= f.button :submit, "connect", :class => 'btn btn-primary' %>
	  </div>


	<% end %>
	</div>
</div>

app/views/interviewee_sessions/show.html.erb
<div class="row-fluid">
    <div class="span8">
        <%= render :partial=>"textedit" %>
    </div>
    <div class="span4">
        <%= render :partial=>"video" %>
        <%= render :partial=>"chat" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src='https://swww.tokbox.com/webrtc/v2.0/js/TB.min.js'></script>
  <title>interviewr</title>
  <!-- Include CodeMirror -->
  <script src="/codemirror/lib/codemirror.js"></script>
  <link rel="stylesheet" href="/codemirror/lib/codemirror.css" />
  <script src="/codemirror/mode/clike/clike.js"></script>
  <script src="/codemirror/mode/javascript/javascript.js"></script>
  <script src="/codemirror/mode/python/python.js"></script>
  <script src="/codemirror/mode/ruby/ruby.js"></script>
  <script src="/codemirror/mode/ocaml/ocaml.js"></script>
  <script src="/codemirror/mode/sql/sql.js"></script>
  <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
  <script src='https://cdn.firebase.com/v0/firebase.js'></script>
  <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js'></script>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans|Electrolize' rel='stylesheet' type='text/css'>


  <meta charset="utf-8" />
</head>
<body>
<% if interviewer? or interviewee? %>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="brand">interviewr</div>
        <% if interviewer? %>
          <div class="navbar-text pull-right end"><%= link_to 'End Session', end_path, :class => "btn btn-mini"%></div>
          <div class="notices pull-right">
            <p class="navbar-text"><%= current_viewer_session.interviewer %></p>
            <p class="navbar-text"><%= current_viewer_session.company %></p>
          </div>
        <% elsif interviewee? %>
        <div class="navbar-text pull-right end"><%= link_to 'Done', done_path, :class => "btn btn-mini"%></div>
        <div class="notices pull-right">
          <p class="navbar-text"><%= interviewer_name %></p>
          <p class="navbar-text"><%= interviewer_co %></p>
        </div>
          <% end %>

    </div>
  </div>
</div>
<% end %>

	<div id="container" class ="container">
    <% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
		<div id="Session" class="row">
		</div>

    <!--div class="span-12"-->
      <%= yield %>
    <!--/div-->
  </div>
</body>
</html>